
default: &default
  adapter: postgresql
  encoding: unicode
  database: banco_de_trabalhos
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  

  
test:
  <<: *default



production:
  <<: *default

  